server:
  port: 9092
spring:
  application:
    name: inventory-service
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/choreography
    username: root
    password: 12345678
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    function:
      definition: handleReserveProductStockRequest;handleCompensateProductStockRequest
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        handleReserveProductStockRequest-in-0:
          destination: ORDER.events